services:
  - type: web
    name: smart-study-planner
    env: python
    plan: free
    buildCommand: pip install -r smartStudyPlanner/requirements.txt
    startCommand: gunicorn --chdir smartStudyPlanner app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_SECRET_KEY
        generateValue: true
